services:
  server:
    build:
      context: . # build from offchain/
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
      - "8765:8765"
      - "8545:8545"

  landlord:
    build:
      context: . # same context → common/ is visible
      dockerfile: client/Dockerfile
    environment:
      - PUBLIC_KEY=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff8
      - SERVER_URI=ws://server:8765
      - CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - server
